INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Books', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Electronics', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Computers', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Clothing', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Home Decor', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Sports Equipment', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Beauty Products', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Toys and Games', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Automotive', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Furniture', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Music Instruments', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Health and Wellness', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Pet Supplies', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Jewelry', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Food and Beverages', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Office Supplies', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Gardening', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Movies and Entertainment', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Fitness Wearables', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Smart Home Devices', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Outdoor Clothing', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Virtual Reality', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Home Office Furniture', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Cycling Gear', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Skincare Products', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Educational Toys', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Car Accessories', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Vintage Furniture', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Piano and Keyboards', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Aromatherapy', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Bird Feeders', NOW());
INSERT INTO tb_categoria(cat_name, data_criacao) VALUES ('Film and TV Memorabilia', NOW());
